### ISSUE TITLE
JavaRAP output null

### ISSUE THREAD

**Issue by saurabhbh21** [WING-NUS/JavaRAP#1]
On executing JavaRAP anaphora resolver, it gives message :

**NPList  empty. Ensure that the parser is working.If it is, run segment() first.**

**Comment by knmnyn** [comment]
The discrepancy you (carefully) observed may be caused by the latest minor code revision that affected the online demo. As we recall, the purpose wasn't to fix mistakes like this. (And it's really a minor fix, so I didn't release the latest code, which is at least 2 to 3 years old.) Another possibility is the parser you are using differs from the one deployed for the demo.

Unfortunately, as interesting as it obviously is, we're sorry to say that we currently cannot look into this issue.
